use http::StatusCode;
use serde::{Deserialize, Serialize};

use crate::gemini::generate_content::types::{
    GeminiCandidate, GeminiModelStatus, GeminiPromptFeedback, GeminiUsageMetadata,
};
use crate::gemini::types::{GeminiApiErrorResponse, GeminiResponseHeaders};

/// Successful response body for Gemini `models.generateContent`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct ResponseBody {
    /// Candidate responses generated by the model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub candidates: Option<Vec<GeminiCandidate>>,
    /// Feedback about prompt safety filtering.
    #[serde(
        rename = "promptFeedback",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub prompt_feedback: Option<GeminiPromptFeedback>,
    /// Token usage metadata for this generation.
    #[serde(
        rename = "usageMetadata",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub usage_metadata: Option<GeminiUsageMetadata>,
    /// Version of the model that served this response.
    #[serde(
        rename = "modelVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub model_version: Option<String>,
    /// Opaque response identifier.
    #[serde(
        rename = "responseId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub response_id: Option<String>,
    /// Lifecycle/status metadata for the model.
    #[serde(
        rename = "modelStatus",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub model_status: Option<GeminiModelStatus>,
}

/// Full HTTP response for Gemini `models.generateContent` endpoint.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GeminiGenerateContentResponse {
    Success {
        /// HTTP status code returned by server (should be `200 OK`).
        #[serde(with = "crate::gemini::types::status_code_serde")]
        stats_code: StatusCode,
        /// Response headers.
        headers: GeminiResponseHeaders,
        /// Successful body.
        body: Box<ResponseBody>,
    },
    Error {
        /// HTTP status code returned by server (typically non-2xx).
        #[serde(with = "crate::gemini::types::status_code_serde")]
        stats_code: StatusCode,
        /// Response headers.
        headers: GeminiResponseHeaders,
        /// Error body.
        body: GeminiApiErrorResponse,
    },
}
